import Head from 'next/head'
import Image from 'next/image'
import { Price } from './components/Price';
import styles from '../styles/Home.module.scss'
import { useDispatch } from "react-redux"
import {addAction} from '../store/price/actions'

export const getStaticProps = async () => {
  const responce = await fetch('https://api.coindesk.com/v1/bpi/currentprice.json');
  const data = await responce.json();

  if (!data) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: { price: data },
  }
}

const Home = ({price}) => {
  const dispatch = useDispatch();
  dispatch(addAction(price));

  return (
    <div className={styles.container}>
      <Head>
        <title>Price of BTC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <h1 className={styles.title}>
          Price BTC 
        </h1>
      </header>

      <main className={styles.main}>
        <Price />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/OlgaStakhova"
          target="_blank"
          rel="noopener noreferrer"
        >
          Autor: Stakhova Olha
        </a>
      </footer>
    </div>
  )
}



export default Home;